export const NotificationTopic = {
    ADDRESS_ADDED: "ADDRESS_ADDED",
    ADDRESS_DELETED: "ADDRESS_DELETED",
    ADDRESS_UPDATED: "ADDRESS_UPDATED",
    EMAIL_UPDATE: "EMAIL_UPDATE",
    PASSWORD_UPDATE: "PASSWORD_UPDATE",
    PHONE_UPDATE: "PHONE_UPDATE",
    FAILED_LOGIN: "FAILED_LOGIN",
};