version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-jwt
    ports:
      - "9411:9411"
    networks:
      - jwt_network

  redis:
    image: redis:latest
    container_name: redis-jwt
    ports:
      - "6379:6379"
    networks:
      - jwt_network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: security
    networks:
      - jwt_network

  jwtSpring:
    image: jwt-spring-app
    container_name: JwtSpring
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - zipkin
      - postgres
    networks:
      - jwt_network

networks:
  jwt_network:
    driver: bridge
