security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXPIRATION_TIME}

discount:
  code:
    threshold: 800.00
spring:
  application:
    name: security
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411



