security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXP_TIME}

discount:
  code:
    threshold: ${DISCOUNT_THRESHOLD}

spring:
  application:
    name: security
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
